example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json 
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')

def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Riona Adani Ghaisani',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml") 

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Riona Adani Ghaisani',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Riona Adani Ghaisani</span>
    </div>
</nav>

<div class = "login" style="text-align:center;">

    <h1 style="margin-top:25px;">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table class="table solid border w-auto" style="margin-left:auto;margin-right:auto;margin-top:25px;">
            <tr>
                <td style="vertical-align:middle;">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td style="vertical-align:middle;">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>
        <td><input class="btn btn-primary" type="submit" value="Login" style="margin-bottom:25px;"></td>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li style="list-style:none">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a class="btn btn-outline-primary" href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<nav class="navbar" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Riona Adani Ghaisani</span>
    </div>
</nav>

<div class = "login" style="text-align:center;">
    
    <h1 style="margin-top:25px;text-align:center;">Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table class="table solid border w-auto" style="text-align:left;margin-right:auto;margin-left:auto;margin-top:25px;">  
                {{ form.as_table }}   
            </table>  
            <td><input class="btn btn-primary" type="submit" name="submit" value="Daftar"/></td> 
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Riona Adani Ghaisani</span>
      <a class="btn btn-primary" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
    </div>
</nav>

<div class="page">
    <table class="table table-bordered w-auto" style="margin-left:auto;margin-right:auto;margin-top:25px;">
        <thead style="background-color: #e3f2fd;">
            <tr>
                <th style="text-align:center">Nama Barang</th>
                <th style="text-align:center">Harga Barang</th>
                <th style="text-align:center">Deskripsi</th>
                </tr>
        </thead>
        <tbody>
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            {% for barang in list_barang %}
            <tr>
                <th>{{barang.nama_barang}}</th>
                <th>{{barang.harga_barang}}</th>
                <th>{{barang.deskripsi}}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <h5 style="text-align:center;margin-top:25px;font-size: medium;">Sesi terakhir login: {{ last_login }}</h5>
</div>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Riona Adani Ghaisani</span>
      <a class="btn btn-primary" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
    </div>
</nav>

<div class="page">
    <table class="table table-bordered w-auto" style="margin-left:auto;margin-right:auto;margin-top:25px;">
        <thead style="background-color: #e3f2fd;">
            <tr>
                <th style="text-align:center">Nama Barang</th>
                <th style="text-align:center">Harga Barang</th>
                <th style="text-align:center">Deskripsi</th>
                </tr>
        </thead>
        <tbody>
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            
        </tbody>
    </table>
    <h5 style="text-align:center;margin-top:25px;font-size: medium;">Sesi terakhir login: {{ last_login }}</h5>
</div>

<script type="text/javascript">
    function refresh() {
        $.ajax({
            type: "GET",
            url: '/wishlist/json/',
            dataType: "json",
            success: function (data) {
                datanya = data
            }
        });
        return datanya;
    }

    function refresh2() {
        var datanya = refresh();
        var itemHtml = "<table> <tr> <th>Nama Barang</th> <th> Deskripsi</th> </tr>"
        for(var i = 0; i < datanya.length; i++){
            var item = datanya[i].fields;
            itemHtml += '<tr> <th>' + item.nama_barang + '</th> <th>' + item.harga_barang + '</th> <th>' + item.deskripsi + '</th> </tr>'
        }
        itemHtml += "</table>";
        $('#lala').html(itemHtml);
    }

</script>


{% endblock content %}